### ISSUE TITLE
Error with firmware 2.9.4

### ISSUE THREAD

**Issue by mlava** [marcelrv/miflora#1]
```
on notification, handle: 0x21 -> 00:00:
on notification, handle: 0x21 -> 00:00:
on notification, handle: 0x21 -> 00:00:

(process:3835): GLib-CRITICAL **: Source ID 4 was not found when attempting to remove it
Error during reafing: <type 'exceptions.RuntimeError'>
on notification, handle: 0x21 -> 00:00:
on notification, handle: 0x21 -> 00:00:
on notification, handle: 0x21 -> 00:00:

(process:3835): GLib-CRITICAL **: Source ID 9 was not found when attempting to remove it
Error during reafing: <type 'exceptions.RuntimeError'>

```

Do you have any idea what causes this?
Cheers!

**Comment by marcelrv** [comment]
Nope, will update one of my sticks to the latest firmware to see if I can replicate it

**Comment by mlava** [comment]
Thanks.

I note that I did have some problems with installing Gattlib on my Raspberry Pi. I had to increase the swapfile to get it to install. I wonder if there is a problem with the Gattlib install given the error message.

If your script works on 2.9.4 for you I will have another look at the Gattlib...

**Comment by mlava** [comment]
Update:
Am successfully using Gattlib for another project, so I don't think that's the issue.
M

**Comment by marcelrv** [comment]
Thanks for that check.
I did not manage to update it before my holidays, so it will need to wait till I'm back. 😢

**Comment by marcelrv** [comment]
I identified the issue and fixed it. For me it now works with v2.9.4
In the newer version the device identifies itself with Flower Care instead of Flower mate, hence it was not queried
